### ISSUE TITLE
Импортировать через * - плохая практика

### ISSUE THREAD

**Issue by hastyulia** [evamarchenkova/audio-editor#8]
https://github.com/evamarchenkova/audio-editor/blob/4ba33006c90eba7c3e770f3dca810420d869e684/logic/audio/audio.py#L5

Лучше явно импортировать то, что тебе надо

**Comment by hastyulia** [comment]
Аналогично 
https://github.com/evamarchenkova/audio-editor/blob/4ba33006c90eba7c3e770f3dca810420d869e684/logic/audio/editing_methods.py#L2

**Comment by hastyulia** [comment]
И еще 
https://github.com/evamarchenkova/audio-editor/blob/4ba33006c90eba7c3e770f3dca810420d869e684/logic/select_the_start_window.py#L11

**Comment by hastyulia** [comment]
И тут
https://github.com/evamarchenkova/audio-editor/blob/4ba33006c90eba7c3e770f3dca810420d869e684/gui/duration_and_volume_changing.py#L10

**Comment by hastyulia** [comment]
Тут тоже
https://github.com/evamarchenkova/audio-editor/blob/4ba33006c90eba7c3e770f3dca810420d869e684/gui/duration_and_playback_speed.py#L10

**Comment by evamarchenkova** [comment]
у меня каждому файлу соответсвует одноименный файл из папки constants. поэтому, при импорте через *, я использую все константы, которые импортируются. в таком случае можно оставить как есть, или все равно переписать без звёздочки?
